# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ben/Desktop/Anki Addon/Dialog_UI/dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

#try to import PyQt5 and then fall back to PyQt4
try:
    from PyQt5 import QtCore
    from PyQt5 import QtGui
    from PyQt5 import QtWidgets
except ImportError:
    from PyQt4 import QtCore
    from PyQt4 import QtGui
    QtWidgets = QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(825, 467)
        Dialog.setStyleSheet("QGroupBox { border: 1px solid grey; font-weight: bold;  }")
        self.layoutMain = QtWidgets.QVBoxLayout(Dialog)
        self.layoutMain.setObjectName("layoutMain")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabOptions = QtWidgets.QWidget()
        self.tabOptions.setObjectName("tabOptions")
        self.layoutOptions = QtWidgets.QHBoxLayout(self.tabOptions)
        self.layoutOptions.setObjectName("layoutOptions")
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutOptions.addItem(spacerItem)
        self.groupBoxSetup = QtWidgets.QGroupBox(self.tabOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSetup.sizePolicy().hasHeightForWidth())
        self.groupBoxSetup.setSizePolicy(sizePolicy)
        self.groupBoxSetup.setObjectName("groupBoxSetup")
        self.layoutSetup = QtWidgets.QFormLayout(self.groupBoxSetup)
        self.layoutSetup.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layoutSetup.setContentsMargins(-1, 30, -1, -1)
        self.layoutSetup.setObjectName("layoutSetup")
        self.labelLeft = QtWidgets.QLabel(self.groupBoxSetup)
        self.labelLeft.setObjectName("labelLeft")
        self.layoutSetup.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelLeft)
        self.lineEditLeft = QtWidgets.QLineEdit(self.groupBoxSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLeft.sizePolicy().hasHeightForWidth())
        self.lineEditLeft.setSizePolicy(sizePolicy)
        self.lineEditLeft.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEditLeft.setObjectName("lineEditLeft")
        self.layoutSetup.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditLeft)
        self.labelRight = QtWidgets.QLabel(self.groupBoxSetup)
        self.labelRight.setObjectName("labelRight")
        self.layoutSetup.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelRight)
        self.lineEditRight = QtWidgets.QLineEdit(self.groupBoxSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRight.sizePolicy().hasHeightForWidth())
        self.lineEditRight.setSizePolicy(sizePolicy)
        self.lineEditRight.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEditRight.setObjectName("lineEditRight")
        self.layoutSetup.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditRight)
        self.labelTop = QtWidgets.QLabel(self.groupBoxSetup)
        self.labelTop.setObjectName("labelTop")
        self.layoutSetup.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelTop)
        self.lineEditTop = QtWidgets.QLineEdit(self.groupBoxSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTop.sizePolicy().hasHeightForWidth())
        self.lineEditTop.setSizePolicy(sizePolicy)
        self.lineEditTop.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEditTop.setObjectName("lineEditTop")
        self.layoutSetup.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditTop)
        self.labelBottom = QtWidgets.QLabel(self.groupBoxSetup)
        self.labelBottom.setObjectName("labelBottom")
        self.layoutSetup.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelBottom)
        self.lineEditBottom = QtWidgets.QLineEdit(self.groupBoxSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBottom.sizePolicy().hasHeightForWidth())
        self.lineEditBottom.setSizePolicy(sizePolicy)
        self.lineEditBottom.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEditBottom.setObjectName("lineEditBottom")
        self.layoutSetup.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditBottom)
        self.labelWidth = QtWidgets.QLabel(self.groupBoxSetup)
        self.labelWidth.setObjectName("labelWidth")
        self.layoutSetup.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelWidth)
        self.lineEditWidth = QtWidgets.QLineEdit(self.groupBoxSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditWidth.sizePolicy().hasHeightForWidth())
        self.lineEditWidth.setSizePolicy(sizePolicy)
        self.lineEditWidth.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEditWidth.setObjectName("lineEditWidth")
        self.layoutSetup.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEditWidth)
        self.labelHeight = QtWidgets.QLabel(self.groupBoxSetup)
        self.labelHeight.setObjectName("labelHeight")
        self.layoutSetup.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelHeight)
        self.lineEditHeight = QtWidgets.QLineEdit(self.groupBoxSetup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditHeight.sizePolicy().hasHeightForWidth())
        self.lineEditHeight.setSizePolicy(sizePolicy)
        self.lineEditHeight.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEditHeight.setObjectName("lineEditHeight")
        self.layoutSetup.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEditHeight)
        self.layoutOptions.addWidget(self.groupBoxSetup)
        self.groupBoxOther = QtWidgets.QGroupBox(self.tabOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxOther.sizePolicy().hasHeightForWidth())
        self.groupBoxOther.setSizePolicy(sizePolicy)
        self.groupBoxOther.setObjectName("groupBoxOther")
        self.layoutOther = QtWidgets.QGridLayout(self.groupBoxOther)
        self.layoutOther.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layoutOther.setContentsMargins(-1, 30, -1, -1)
        self.layoutOther.setObjectName("layoutOther")
        self.radioButtonKeep = QtWidgets.QRadioButton(self.groupBoxOther)
        self.radioButtonKeep.setObjectName("radioButtonKeep")
        self.buttonGroupImage = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroupImage.setObjectName("buttonGroupImage")
        self.buttonGroupImage.addButton(self.radioButtonKeep)
        self.layoutOther.addWidget(self.radioButtonKeep, 4, 0, 1, 1)
        self.radioButtonHtml = QtWidgets.QRadioButton(self.groupBoxOther)
        self.radioButtonHtml.setObjectName("radioButtonHtml")
        self.buttonGroupOutput = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroupOutput.setObjectName("buttonGroupOutput")
        self.buttonGroupOutput.addButton(self.radioButtonHtml)
        self.layoutOther.addWidget(self.radioButtonHtml, 6, 0, 1, 1)
        self.radioButtonInch = QtWidgets.QRadioButton(self.groupBoxOther)
        self.radioButtonInch.setObjectName("radioButtonInch")
        self.buttonGroupUnits = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroupUnits.setObjectName("buttonGroupUnits")
        self.buttonGroupUnits.addButton(self.radioButtonInch)
        self.layoutOther.addWidget(self.radioButtonInch, 2, 0, 1, 1)
        self.radioButtonPdf = QtWidgets.QRadioButton(self.groupBoxOther)
        self.radioButtonPdf.setObjectName("radioButtonPdf")
        self.buttonGroupOutput.addButton(self.radioButtonPdf)
        self.layoutOther.addWidget(self.radioButtonPdf, 6, 1, 1, 1)
        self.radioButtonSplit = QtWidgets.QRadioButton(self.groupBoxOther)
        self.radioButtonSplit.setObjectName("radioButtonSplit")
        self.buttonGroupImage.addButton(self.radioButtonSplit)
        self.layoutOther.addWidget(self.radioButtonSplit, 4, 1, 1, 1)
        self.radioButtonMm = QtWidgets.QRadioButton(self.groupBoxOther)
        self.radioButtonMm.setObjectName("radioButtonMm")
        self.buttonGroupUnits.addButton(self.radioButtonMm)
        self.layoutOther.addWidget(self.radioButtonMm, 2, 1, 1, 1)
        self.labelUnits = QtWidgets.QLabel(self.groupBoxOther)
        self.labelUnits.setObjectName("labelUnits")
        self.layoutOther.addWidget(self.labelUnits, 1, 0, 1, 2)
        self.labelImage = QtWidgets.QLabel(self.groupBoxOther)
        self.labelImage.setObjectName("labelImage")
        self.layoutOther.addWidget(self.labelImage, 3, 0, 1, 2)
        self.labelOutput = QtWidgets.QLabel(self.groupBoxOther)
        self.labelOutput.setObjectName("labelOutput")
        self.layoutOther.addWidget(self.labelOutput, 5, 0, 1, 2)
        self.layoutOptions.addWidget(self.groupBoxOther)
        spacerItem1 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutOptions.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabOptions, "")
        self.tabStyle = QtWidgets.QWidget()
        self.tabStyle.setObjectName("tabStyle")
        self.layoutStyle = QtWidgets.QVBoxLayout(self.tabStyle)
        self.layoutStyle.setObjectName("layoutStyle")
        self.labelStyle = QtWidgets.QLabel(self.tabStyle)
        self.labelStyle.setStyleSheet("QLabel { background-color: lightgrey; border: 2px inset grey }")
        self.labelStyle.setWordWrap(True)
        self.labelStyle.setObjectName("labelStyle")
        self.layoutStyle.addWidget(self.labelStyle)
        self.textEdit = QtWidgets.QTextEdit(self.tabStyle)
        self.textEdit.setObjectName("textEdit")
        self.layoutStyle.addWidget(self.textEdit)
        self.pushButtonRestore = QtWidgets.QPushButton(self.tabStyle)
        self.pushButtonRestore.setObjectName("pushButtonRestore")
        self.layoutStyle.addWidget(self.pushButtonRestore, 0, QtCore.Qt.AlignLeft)
        self.tabWidget.addTab(self.tabStyle, "")
        self.layoutMain.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutMain.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBoxSetup.setTitle(_translate("Dialog", "Page Setup:"))
        self.labelLeft.setText(_translate("Dialog", "Left Margin"))
        self.labelRight.setText(_translate("Dialog", "Right Margin"))
        self.labelTop.setText(_translate("Dialog", "Top Margin"))
        self.labelBottom.setText(_translate("Dialog", "Bottom Margin"))
        self.labelWidth.setText(_translate("Dialog", "Page Width"))
        self.labelHeight.setText(_translate("Dialog", "Page Height"))
        self.groupBoxOther.setTitle(_translate("Dialog", "Other Options:"))
        self.radioButtonKeep.setText(_translate("Dialog", "Keep layout"))
        self.radioButtonHtml.setText(_translate("Dialog", "html only"))
        self.radioButtonInch.setText(_translate("Dialog", "Inches"))
        self.radioButtonPdf.setText(_translate("Dialog", "html and pdf"))
        self.radioButtonSplit.setText(_translate("Dialog", "Reposition Images"))
        self.radioButtonMm.setText(_translate("Dialog", "mm"))
        self.labelUnits.setText(_translate("Dialog", "Units used for page layout:"))
        self.labelImage.setText(_translate("Dialog", "Image handling (intended for landscape):"))
        self.labelOutput.setText(_translate("Dialog", "Output file format:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOptions), _translate("Dialog", "Page Setup"))
        self.labelStyle.setText(_translate("Dialog", "The following variables represent values that can be used in the CSS style:\n"
"$HEIGHT = Page Height minus the Top and Bottom Margins\n"
"$WIDTH = Page Width minus the Left and Right Margins\n"
"$UNITS = Units of choice, in or mm"))
        self.pushButtonRestore.setText(_translate("Dialog", "Restore Original"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStyle), _translate("Dialog", "Edit Css Style"))

